### PR TITLE
create github action workflows

### PR DESCRIPTION
**Pull request by shapiromatron**

### CODE REVIEW

**Comment by JanMalte** [comment]
@shapiromatron are you still working on it?

**Comment by shapiromatron** [comment]
I'm stuck w/ webpack4 and node18 - it looks like a common problem here: https://github.com/webpack/webpack/issues/14532

Could we updates to only support webpack5?

**Comment by shapiromatron** [comment]
@JanMalte I made some progress! I skipped webpack4 tests in CI and changed the base branch to the 2.0 release branch; , and got everything working except for one breaking test. The test pass suite works for me locally and no tests are skipped, but this test error looks real to me?

https://github.com/shapiromatron/webpack-bundle-tracker/actions/runs/4833291812/jobs/8613106103#step:5:23

```
FAIL tests/webpack5.test.js (5.767s)
  ● BundleTrackerPlugin bases tests › It should show compressed assets

    TypeError: Cannot read properties of undefined (reading 'compilation')

      11 | function testPlugin(webpack, webpackConfig, expectedResults, outputFile, done, expectErrors, expectWarnings) {
      12 |   webpack(webpackConfig, (err, stats) => {
    > 13 |     const compilationErrors = (stats.compilation.errors || []).join('\n');
         |                                      ^
      14 |     const compilationWarnings = (stats.compilation.warnings || []).join('\n');
      15 |
      16 |     expect(err).toBeFalsy();

```

**Comment by shapiromatron** [comment]
thanks for finishing this one off for me, it looks great!!!

**Pull request merged**
