### PR TITLE
Strip control codes in error messages.

### PR DESCRIPTION
**Pull request by aaugustin**

### CODE REVIEW

**Comment by aaugustin** [comment]
This is a follow-up to https://github.com/owais/django-webpack-loader/pull/39.

It looks like you were just missing `stripAnsi` in one location.

**Comment by aaugustin** [comment]
While we're there, I find it surprising to depend on [a package](https://github.com/chalk/strip-ansi) which only provides a 60-char function and itself depends on [another package](https://github.com/chalk/ansi-regex) which only provides an 80-char regex and manages to get it wrong (but not in a way that affects me). You're going through all this just to avoid implementing a one liner:

```
stripAnsi = message => message.replace(
    new RegExp('(?:\\x1b\\x5b|\\x9b)[\\x30-\\x3f]*[\\x20-\\x2f]*[\\x40-\\x7e]', 'g'), '')
```

I assume it makes sense from some perspective, but it just sent me on a wrong track for longer than I'm willing to admit :-(

Anyway, the fix above should suffice, so let's leave it there :-)

**Comment by SBoudrias** [comment]
@aaugustin that's the node way.

If you think that module have a bug, well then open a bug or a PR, we you'll fix it on over a 100 other projects - to me that's way more powerful than an inline regex.

**Comment by aaugustin** [comment]
@SBoudrias I get the idea of packaging reusable modules; I was pointing out that there's a point of diminishing returns. In my opinion, packaging each line of code separately (like the ansi-\* packages do) takes it too far.

**Pull request merged**
