### PR TITLE
Run CI on CircleCI

### PR DESCRIPTION
**Pull request by quinox**
Addresses the CI discussion of #73; supersedes #95.

The CI runs against 12 (oldest still-supported LTS), LTS (14 right now) and current (16 right now). See [my CircleCI](https://app.circleci.com/pipelines/github/ytec-nl/webpack-bundle-tracker?branch=master) for how it will look.

As can seen in [this experiment](https://app.circleci.com/pipelines/github/ytec-nl/webpack-bundle-tracker/14/workflows/da97489b-3696-43b2-93a1-5c991ab665dc/jobs/56) the CI would have caught the problem as described in #73 .

Note! Please update the badge in `README.md` during merging, it's pointing to my Github right now

### CODE REVIEW

**Comment by fjsj** [comment]
Thanks @quinox , this looks great. Could you please allow me edits (check https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)? I need it to update the badge.

**Comment by quinox** [comment]
I wish I knew how: I don't see the checkbox from the screenshot anywhere. The help says _On user-owned forks_, I made the fork in my organization, maybe that's my problem?

I've updated the badge in my repo to use `django-webpack` instead of `ytec-nl`, if you want more changes I'm guessing you can fork my repo to your personal account and modify it further there.

**Comment by fjsj** [comment]
yep, from orgs I think that doesn't work. no worries, that's fine, thanks. merging now

**Review by fjsj — APPROVED** [review]
LGTM

**Pull request merged**
