### PR TITLE
Support webpack 4 only

### PR DESCRIPTION
**Pull request by melck**
Rewrite of plugin into es6 syntax.

Handle splitChunks options of Webpack 4. 

BREAKING CHANGE: Drop support for Webpack version < 4

Related to #52

### CODE REVIEW

**Comment by melck** [comment]
@owais I have tested my work, what do you think about this changes ?

**Comment by owais** [comment]
Thanks. Code looks good. Does this change the output format of the stats file in any way? Can you describe that in case. 

Since we are dropping support, this is a nice opportunity to make any changes to the stats file schema so more use cases can be accommodated. 

Generally I'd like to us to take a direction to make the stats file less specific to webpack. It should just contains references to assets that a webserver can later retrieve. If we are able to do that, we can then further protect non-JS web servers from the constant change in JS land but this needs further discussion and probably in a different place.

**Comment by melck** [comment]
The output format change a little but no breaking change. For exemple with full options, for two app we have :
```json
{
    "status": "done",
     "publicPath": "http://localhost:3000/assets/",
     "startTime": 1578131712,
     "endTime": 1578131912,
    "chunks": {
            "app1": [
              {
                "name": "vendors-zeazeazae62165416.js",
                "publicPath": "http://localhost:3000/assets/js/vendors-zeazeazae62165416.js",
                "path": "http://localhost:3000/assets/js/vendors-zeazeazae62165416.js",
                "integrity": "sha256-SHA256 sha384-SHA384 sha512-SHA512"
              },
              {
                "name": "commons-gfhrtyhrh45665.js",
                "publicPath": "http://localhost:3000/assets/js/commons-gfhrtyhrh45665.js",
                "path": "http://localhost:3000/assets/js/commons-gfhrtyhrh45665.js",
                "integrity": "sha256-SHA256 sha384-SHA384 sha512-SHA512"
              },
              {
                "name": "app1-tyujtyjgh6546879.css",
                "publicPath": "http://localhost:3000/assets/js/app1-tyujtyjgh6546879.css",
                "path": "http://localhost:3000/assets/js/app1-tyujtyjgh6546879.css",
                "integrity": "sha256-SHA256 sha384-SHA384 sha512-SHA512"
              },
              {
                "name": "app1-zeazeazae62165416.js",
                "publicPath": "http://localhost:3000/assets/js/app1-zeazeazae62165416.js",
                "path": "http://localhost:3000/assets/js/app1-zeazeazae62165416.js",
                "integrity": "sha256-SHA256 sha384-SHA384 sha512-SHA512"
              }
            ],
            "app2": [
              {
                "name": "vendors-zeazeazae62165416.js",
                "publicPath": "http://localhost:3000/assets/js/vendors-zeazeazae62165416.js",
                "path": "http://localhost:3000/assets/js/vendors-zeazeazae62165416.js",
                "integrity": "sha256-SHA256 sha384-SHA384 sha512-SHA512"
              },
              {
                "name": "commons-gfhrtyhrh45665.js",
                "publicPath": "http://localhost:3000/assets/js/commons-gfhrtyhrh45665.js",
                "path": "http://localhost:3000/assets/js/commons-gfhrtyhrh45665.js",
                "integrity": "sha256-SHA256 sha384-SHA384 sha512-SHA512"
              },
              {
                "name": "app2-erzterte46544.css",
                "publicPath": "http://localhost:3000/assets/js/app2-erzterte46544.css",
                "path": "http://localhost:3000/assets/js/app2-erzterte46544.css",
                "integrity": "sha256-SHA256 sha384-SHA384 sha512-SHA512"
              },
              {
                "name": "app2-dfgdfgs54645.js",
                "publicPath": "http://localhost:3000/assets/js/app2-dfgdfgs54645.js",
                "path": "http://localhost:3000/assets/js/app2-dfgdfgs54645.js",
                "integrity": "sha256-SHA256 sha384-SHA384 sha512-SHA512"
              }
            ]
          }
    }
}
```

It will show only entrypoint chunkGroup, not child chunk load on demand.

**Comment by owais** [comment]
Should path a be file-system path instead of a URL?

**Comment by melck** [comment]
Yes it was a mistake when copy / paste.

**Comment by owais** [comment]
Sounds good. We'll also need to add test cases to django-webpack-loader for webpack4 to ensure nothing breaks there.

**Pull request merged**
