### PR TITLE
Features for v1.0.0

### LINKED ISSUE #52: v1.0.0
Hello,

Now that we have tests. I want to rewrite plugin to es6 syntax and add following changes :
- Support only webpack >4
- Handle splitChunk option of Webpack to add files related of a chunk.
- Add `integrity` option to handle https://www.w3.org/TR/SRI/

What do you think ? I'll start a pull request to show you changes that i want to made

### LINKED ISSUE #56: Explore using loaders to track assets
https://github.com/owais/webpack-bundle-tracker/pull/17#issuecomment-346741678

### PR DESCRIPTION
**Pull request by melck**
- Load all assets in assets entry with name, path, publicPath details.
- Reduce a chunk entry to refer a list of asset's name
- Add options `integrity` and `integrityHashes` to implement w3c SRI for
each asset.

BREAKING CHANGE: JSON structure of stat file changes to add assets produced by webpack. Chunks entry
has beed changed to contain a list of asset name per chunk. You need to
change how assets are resolved for each chunk.

resolve #52, resolve #56

### CODE REVIEW

**Comment by melck** [comment]
@owais Could you review this and made another alpha version if ok ?

**Comment by melck** [comment]
@owais Any news :) ?

**Comment by owais** [comment]
Done https://www.npmjs.com/package/webpack-bundle-tracker/v/1.0.0-alpha.1

**Comment by jonalxh** [comment]
Perfect, I was waiting for it.

**Pull request merged**
