### PR TITLE
Fix corruption after hot updates due to misuse of lodash.merge

### PR DESCRIPTION
**Pull request by andersk**
`lodash.merge` has the following undesired behavior on arrays:

```js
> chunks = { main: ['a', 'b', 'c', 'd', 'e'] }
{ main: [ 'a', 'b', 'c', 'd', 'e' ] }
> merge(chunks, { main: ['foo', 'bar'] })
{ main: [ 'foo', 'bar', 'c', 'd', 'e' ] }
```

Instead of using `lodash.merge` (#98), specify exactly which objects need to be combined using `lodash.assign`.

Cc @TomekStaszkiewicz @joaopslins

### CODE REVIEW

**Comment by fjsj** [comment]
Thanks @andersk .
Any easy regression test we can add here to prevent such wrong behavior again?

**Comment by andersk** [comment]
Added tests and fixed the TypeScript typings.

(Why aren’t the CircleCI tests running on pull requests?)

**Review by fjsj — APPROVED** [review]
LGTM, merging, thank you very much.

**Comment by fjsj** [comment]
Released at 1.2.0

**Pull request merged**
