### PR TITLE
Add support for webpack v4 hooks api

### PR DESCRIPTION
**Pull request by fiveletter**
For anyone that ran into this issue as well.

### CODE REVIEW

**Comment by owais** [comment]
@fiveletter I'm not very familiar with webpack API since version 2. Will this break backward compatibility with older versions?

**Comment by fiveletter** [comment]
It should be backwards compatible since the code branches it's logic on `compiler.hooks` check.

I based this change off of a similar code edit made by another repository.

**Comment by owais** [comment]
OK. Thanks. I don't have the time to review thoroughly. Will release a beta version over the weekend.

**Comment by Lexicality** [comment]
WFM

**Pull request merged**
